version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production_kittygram:/var/lib/postgresql/data
  backend:
    image: tekut/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
  frontend:
    env_file: .env
    image: tekut/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: tekut/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/